name: Viiddo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^1.1.1
  date_format: ^1.0.8
  dio: ^3.0.9
  equatable: ^1.1.1
  flushbar: ^1.10.4
  flutter_bloc: ^4.0.0
  #  The below is a fix for an issue related to Flutter v 1.16.4 onward and the 1.3.5 release of flutter_datetime_picker
  #  See https://github.com/Realank/flutter_datetime_picker/issues/135
  #  Note there are a number of duplicate issues on the GitHub for this problem and some describe the problem better, but this one describes the solution in the simplest terms
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  image_picker: ^0.6.6+4
  image: ^2.1.13
  json_annotation: ^3.0.1
  package_info: ^0.4.0+18
  path_provider: ^1.6.9
  shared_preferences: ^0.5.7+3
  simple_moment: ^1.0.4
  unicorndial: ^1.1.5
  validate: ^1.7.0
  date_utils: ^0.1.0+3
  simple_gesture_detector: ^0.1.4
  geolocator: ^5.3.1
  device_info: ^0.4.2+4
  permission_handler: ^5.0.0+hotfix.6
  modal_progress_hud: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

  flutter_launcher_icons: ^0.7.5
  url_launcher: ^5.4.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 500

    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 500

    - family: Roboto-Italic
      fonts:
        - asset: fonts/Roboto-Italic.ttf
          weight: 500

    - family: Roboto-Black
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 500

    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 500

    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500

    - family: Roboto-Thin
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 500
